
server:
  port: 8071

spring:
  application:
    name: feign
  profiles:
    active: dev
    main:
      allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123

  redis:
    port: 6379
    host: 127.0.0.1
    database: 0
    timeout: 5000ms
    jedis:
      pool:
        max-active: 200
        max-wait: -1ms
        max-idle: 10
        min-idle: 0

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka


feign:
  hystrix:
    enabled: false