server:
  port: 8091

spring:
  application:
    name: glht-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gs-cj/config.git
          search-paths: /
          username: gs-cj
          password: zhiweiziji0720
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf-8
=======
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&serverTimezone=GMT%2B8
>>>>>>> 11b33f566d80ebfa8b6f364151647756d846de5a
    username: root
    password: 123

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka